# Generated by Django 4.0.6 on 2022-08-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=250)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('date', models.DateTimeField()),
                ('currency', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FileClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activ', models.FloatField()),
                ('passive', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activ', models.FloatField()),
                ('passive', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TurnOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('content_characteristics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.contentcharacteristics')),
            ],
        ),
        migrations.CreateModel(
            name='FileContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(max_length=250)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.fileclasses')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.files')),
                ('incoming_balance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.incomingbalance')),
                ('outgoing_balance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.outgoingbalance')),
                ('turn_over_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.turnover')),
            ],
        ),
    ]
